my_guests = ["Sandy", "Mandy", "Vandy"]
print("Welcome to my party " + my_guests[0].title() + "!")
print("Welcome to my party " + my_guests[1].title() + "!")
print("Welcome to my party " + my_guests[2].title() + "!")
absent = my_guests.pop(1)
print(absent.title() + " - can't come.")
my_guests.insert(1, "Andy")
print("Welcome to my party " + my_guests[0].title() + "!")
print("Welcome to my party " + my_guests[1].title() + "!")
print("Welcome to my party " + my_guests[2].title() + "!")
