my_guests = ["Sandy", "Mandy", "Vendy"]
print("Welcome to my party " + my_guests[0].title() + "!")
print("Welcome to my party " + my_guests[1].title() + "!")
print("Welcome to my party " + my_guests[2].title() + "!")
absent = my_guests.pop(1)
print(absent.title() + " - can't come.")
my_guests.insert(1, "Andy")
print("Welcome to my party " + my_guests[0].title() + "!")
print("Welcome to my party " + my_guests[1].title() + "!")
print("Welcome to my party " + my_guests[2].title() + "!")
print("More guests has arrived.")
my_guests.insert(0, "Mary")
my_guests.insert(2, "Bary")
my_guests.append("Jack")
print("Welcome to my party " + my_guests[0].title() + "!")
print("Welcome to my party " + my_guests[1].title() + "!")
print("Welcome to my party " + my_guests[2].title() + "!")
print("Welcome to my party " + my_guests[3].title() + "!")
print("Welcome to my party " + my_guests[4].title() + "!")
print("Welcome to my party " + my_guests[5].title() + "!")
print("Party for 2 people.")
canceled_user = my_guests.pop(5)
print("Sorry " + canceled_user + ", i need cancel invitation.")
canceled_user = my_guests.pop(4)
print("Sorry " + canceled_user + ", i need cancel invitation.")
canceled_user = my_guests.pop(3)
print("Sorry " + canceled_user + ", i need cancel invitation.")
canceled_user = my_guests.pop(2)
print("Sorry " + canceled_user + ", i need cancel invitation.")
print("The invitation still remains valid for you - " + my_guests[1].title())
print("The invitation still remains valid for you - " + my_guests[0].title())
del my_guests[1]
del my_guests[0]
print(my_guests)
